# Incluir apenas o conteúdo em pt-br
include:
  - pt-br

# Excluir os demais idiomas e o redirecioamento
exclude:
  - en
  - index.html

# Permalinks simples
defaults:
  - scope:
      path: "pt-br"
      type: "pages"
    values:
      layout: default
