title: "Opus Open Finance"
description: "Documentação que descreve a Plataforma Opus Open Finance, incluindo integração e implantação"

url: "https://opusopenfinance.github.io"
baseurl: "/Documentation"

markdown: kramdown
highlighter: rouge

remote_theme: null
theme: "just-the-docs"

just_the_docs:
  layout: default
  enable_cache: false
  navigation_structure: true
  show_toc: true
  toc_levels: 1..3
  sidebar:
    position: fixed
  search_enabled: true
  custom_js:
    - /assets/js/open-links.js
    - /assets/js/language-redirect.js
  custom_css: assets/css/custom.css
  include_head: head_custom.html
  header_custom: true

include:
  - _layouts

footer_content: null
aux_links: null

callouts_level: quiet
callouts:
  aviso:         { title: Aviso, color: red }
  destaque:      { color: yellow }
  importante:    { title: Importante, color: blue }
  novo:          { title: Novo, color: green }
  nota:          { title: Nota, color: purple }
  warning:       { title: Warning, color: red }
  highlight:     { color: yellow }
  important:     { title: Important, color: blue }
  new:           { title: New, color: green }
  note:          { title: Note, color: purple }
