# Nome do workflow que aparecerá na aba Actions do GitHub
name: Deploy Jekyll site to Pages

# Define os gatilhos para execução automática ou manual
on:
  push:
    branches: ["main"]       # Executa sempre que houver push para o branch main
  workflow_dispatch:         # Permite executar manualmente pelo GitHub

# Permissões mínimas necessárias para o deploy via GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que só uma execução ocorra por vez (útil se vários pushes acontecerem)
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente Linux padrão

    steps:
      # Passo 1: Clona o repositório
      - name: 📥 Checkout
        uses: actions/checkout@v4

      # Passo 2: Instala Ruby e as dependências do Bundler a partir do diretório docs/
      - name: 💎 Setup Ruby (com bundler no diretório correto)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'            # Versão do Ruby compatível com seu ambiente local
          bundler-cache: true            # Cache das gems para builds futuros
          working-directory: docs        # ⚠️ Importante: onde está o Gemfile

      # Passo 3: Prepara o ambiente interno de GitHub Pages
      - name: ⚙️ Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      # Passo 4: Executa seu script de build multilíngue
      - name: 🛠️ Build multilíngue com githubpages.sh
        run: |
          chmod +x docs/githubpages.sh   # Garante permissão de execução
          ./docs/githubpages.sh          # Executa o script dentro de /docs

      # Passo 5: Faz upload do site gerado para ser usado no deploy
      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site                    # Diretório de saída definido no script

  # Job separado para publicar no GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build  # Aguarda a conclusão do job de build acima

    steps:
      - name: 🚀 Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
